version: 2

# cSpell:ignore circleci, chmod

aliases:
  - &container_config
    docker:
      - image: circleci/node:10.13.0
    working_directory: /home/circleci/project

  - &node_modules_cache_params
    key: v2-node_modules-{{ .Branch }}-{{ checksum "./package-lock.json" }}
    paths:
      - node_modules

  - &update_npm
  name: Show system information.
  command: npm install -g -npm

  - &show_information
    name: Show system information.
    command: |
      echo "Node $(node -v)"
      echo "Npm $(npm -v)"

  - &restore_cache
    name: Restore Cache.
    <<: *node_modules_cache_params

  - &npm_install
    name: Set up to gas clasp environment.
    command: npm install

  - &save_cache
    name: Saving Cache.
    <<: *node_modules_cache_params

  - &build_permission_setting
    name: Setting Build-CI Permission.
    command: chmod +x ./.scripts/build-ci.sh

  - &create_env
    name: Create .env File..
    command: ./.scripts/build-ci.sh

  - &lint
    name: Run Lint.
    command: npm run lint

  - &test
    name: Run Test.
    command: npm run test

  - &build
    name: Run webpack build.
    command: npm run build

  - &deploy_permission_setting
    name: Setting Deploy-CI Permission.
    command: chmod +x ./.scripts/deploy-ci.sh

  - &deploy
    name: Deploy to GAS.
    command: ./.scripts/deploy-ci.sh

jobs:
  build:
    <<: *container_config
    steps:
      - checkout
      - run: *update_npm
      - run: *show_information
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
      - run: *build_permission_setting
      - run: *create_env
      - run: *lint
      - run: *test
      - run: *build
  build_deploy:
    <<: *container_config
    steps:
      - checkout
      - run: *update_npm
      - run: *show_information
      - restore_cache: *restore_cache
      - run: *npm_install
      - save_cache: *save_cache
      - run: *build_permission_setting
      - run: *create_env
      - run: *lint
      - run: *test
      - run: *build
      - run: *deploy_permission_setting
      - run: *deploy

workflows:
  version: 2
  build_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
  build_deploy_workflow:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: master
