name: Auto Security Fix
on:
  schedule:
    #    - cron: '0 3 * * 3' # 毎週水曜日の正午に実行 ( 12+JST = 3+UTC )
    - cron: '*/15 * * * *'

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/checkout@master

      - name: Git Checkout
        run: |
          today=$(date "+%Y%m%d")
          export BRANCH_NAME="securityFix-${today}"
          git checkout -b ${BRANCH_NAME}

      - run: npm audit fix

      - name: Check diff
        run: |
          git diff --stat package-lock.json
          if ! git diff --stat package-lock.json | grep "changed" 2>&1; then
            echo "Already up to date."
            exit 0
          fi

      - name: Commit changes
        run: |
          git config --global user.email "${{ secrets.AUTHOR_EMAIL }}"
          git config --global user.name "${{ secrets.AUTHOR_NAME }}"
          git add package-lock.json
          git commit -m "SecurityFix"
          git push --set-upstream origin "${BRANCH_NAME}""

      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB }}
