name: Auto Merge at Security Fix Pull Request
on:
  pull_request:
    branches:
      - "securityFix-*"

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@2c8e667a3386187418587517e5bfe33470d19b5b"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
