name: Auto Approve for Security Fix Pull Request
on:
  pull_request:
    branches:
      - "securityFix-*"

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
