name: Create Security Fix Pull Request
on:
  schedule:
    - cron: "0 3 * * 3" # 毎週水曜日の正午に実行 ( 12+JST = 3+UTC )

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - uses: actions/checkout@master

      - run: npm install -g npm

      - run: npm audit fix

      - name: Check diff
        run: |
          git diff --stat package-lock.json
          if ! git diff --stat package-lock.json | grep "changed" 2>&1; then
            echo "Already up to date."
            exit 0
          fi

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1.7.0
        with:
          title: Security Update into master.
          label: Auto-PR
          branch: securityFix
          token: ${{ secrets.GITHUB }}
