name: Create Security Fix Pull Request
on:
  schedule:
    #    - cron: '0 3 * * 3' # 毎週水曜日の正午に実行 ( 12+JST = 3+UTC )
    - cron: '*/15 * * * *'

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - uses: actions/checkout@master

      - run: npm audit fix

      - name: Check diff
        run: |
          git diff --stat package-lock.json
          if ! git diff --stat package-lock.json | grep "changed" 2>&1; then
            echo "Already up to date."
            exit 0
          fi

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v1.7.0
        with:
          title: [Automate] Security Update into master. - $(date "+%Y%m%d")
          label: Auto-PR
          branch: securityFix-$(date "+%Y%m%d")
          token: ${{ secrets.GITHUB }}
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
